### ISSUE TITLE
Crée une équipe

### ISSUE THREAD

**Issue by geoffrey0170** [ProjectWarbot/Warbot-Online#1]
Crée un formulaire, validation d'un formulaire.
Test en base de donnée de l'existence d'une équipe avec le même identifiant. Ajout a la BDD.
Retourné le résultat d'ajout.
Affichier la page équipe.

**Comment by sbeugnon** [comment]
Formulaire done.
Validation de formulaire done.
Test en base de donnée done.
Redirection vers la page de développement si succès.
Redirection vers la page de création si échec. (Besoin de rajouter le message d'erreur à l'affichage)
(Sébastien)
