### ISSUE TITLE
Bloquer les agents en cours d'édition

### ISSUE THREAD

**Issue by geoffrey0170** [ProjectWarbot/Warbot-Online#12]
Gérer un verrou par websocket surveillant l'édition de code des agents dans une même équipe.

**Comment by sbeugnon** [comment]
Grâce à l'évolution du contrôleur CodeEditorController en accès par WebSocket, on peut désormais placer des verrous sur le code des agents.

Il faut pour cela dans le service CodeEditorService analyser les événements de la websocket pour les déconnexion d'utilisateur pour déverrouiller le code pris.

**Comment by quentinphilbert** [comment]
Je peux m'en occuper si ca vous dit.
