### ISSUE TITLE
Messages transmis au client pour une partie Warbot

### ISSUE THREAD

**Issue by Falindir** [ProjectWarbot/Warbot-Online#17]
Avoir la taille des dessins des agents de warbot, de la map, des percepts (longueur et largeur du cone)

**Comment by sbeugnon** [comment]
Informations transmises sur le réseau :

(x l'information n'est transmise qu'une seuile fois,
 v l'information peut être retransmise suite à une modification)

## Agent

name (key) : String
type (x) : String
x (v) : double
y (v) : double
team(x : key dans Team) : String
lifeP (v) : double
angle (v) : double
colorDebug (v) : {"r":255,"g":255,"b":255}
messageDebug (v) : String
~~toDestroy (x : envoyé pour la destruction de l'agent)~~
state (x : -1 pour détruire l'agent, +1 pour créer un nouvel agent)

## Team

name (x) : String
Color (x) :  {"r":255,"g":255,"b":255}

## Environment

width (x) (int)
height (x) (int)
mapName (x) (string)
walls (x) : Agent

**Comment by sbeugnon** [comment]
## Liste des messages

### Format (json)

{
"header": "<!code>",
"content": {...} ou [...,...]
}

### Entête de message ("header")

"init" : Message initialisant une partie (Envoi de l'environnement sous la forme Environment, des équipes sous la forme Team, et des Agents actifs)

"agent" : Message indiquant les informations d'un agent (toutes s'il s'agit de la première fois) qui ont été modifié durant le "tick".

"synchro" : Message contenant l'ensemble des agents vivants durant ce tour (sert à la resynchronisation de l'affichage) qui est envoyé tout les X "ticks". (X un nombre random entre 100 et 300)

"end": Message indiquant la fin d'une partie (avec quelle condition de fin activée)

### Contenu d'un message ("content")

"init" : 
{ "environment": Environment,
 "teams": [Team,Team],
"agents":[Agent,...,Agent] 
}

"agent" :
{ Agent }

"synchro" :
[ Agent, ..., Agent]

"end" :
A voir

**Comment by sbeugnon** [comment]
Gestion des messages terminée. (Jimmy)
