### ISSUE TITLE
Message client to server

### ISSUE THREAD

**Issue by Falindir** [ProjectWarbot/Warbot-Online#18]
- Création d'une partit warbot
- Récupérer les Team d'un utilisateur (code agent)
- Se connecter / Se deconnecter
- Créer une team / Supprimer une team
- (optional) Récupérer l'elo du joueur (recalcul apres une partit)
- Gestion profil (ajout / suppression de données)
- Provoquer un utilisateur (en général une autre team d'agent)
- Passer premium

**Comment by Falindir** [comment]
- Sauvegarder son code

**Comment by sbeugnon** [comment]
(ok veut dire que la requête js devra être implémentée)
- Création de partie (ok)
- Récupérer le code d'une équipe (ok)
- Sauvegarder le code d'une équipe (ok)
- Se connecter / Se déconnecter (non cela n'a rien avoir avec les messages asynchrônes)
- Créer une équipe / Supprimer une équipe (non cela n'a rien avoir avec les messages asynchrônes)
- Récupérer "l'élo du joueur" (non cela n'a rien avoir avec les messages asynchrônes, de plus le "elo" se trouve dans une entité "Party" donc l'élo est lié à une équipe)
- Gestion profil (non cela n'a rien avoir avec les messages asynchrônes)
- Provoquer un utilisateur (?) (S'il s'agit de lancer une partie contre l'équipe d'un autre utilisateur alors, non cela n'a rien avoir avec les messages asynchrônes)
- Passer premium (non cela n'a rien avoir avec les messages asynchrônes)

**Comment by sbeugnon** [comment]
Le contrôleur CodeEditorController s'occupe de la gestion du code des équipes pour l'éditeur de texte. Simple contrôleur avec les appels asynchrônes autorisés.

Tandis que le contrôleur WebGameSocket s'occupe de la gestion des sockets permettant la visualisation des parties. Il utilise notamment SockJS pour le client et Stomp afin de s'assurer du contenu envoyé par le client vers le serveur.
