### ISSUE TITLE
Charger le code d'une équipe dans l'éditeur client

### ISSUE THREAD

**Issue by geoffrey0170** [ProjectWarbot/Warbot-Online#2]
Aller chercher le code en base de données.
L'afficher dans la page web.

**Comment by sbeugnon** [comment]
La recherche en base de données est terminée.
Il faut cependant modifier le contrôleur CodeEditorController car ce dernier en REST provoque des collisiond avec le templateResolver de Thymeleaf provoquant une erreur 500 (où le OutputStream est appelé deux fois)
