### ISSUE TITLE
"Salle d'entrainement" utilisation des configurations initiales

### ISSUE THREAD

**Issue by sbeugnon** [ProjectWarbot/Warbot-Online#26]
Il s'agit d'utiliser les configurations produites dans l'éditeur de configurations et les lancer avec le code de l'équipe courante de l'utilisateur. L'utilisateur peut alors modifier le code de ses agents avec l'éditeur de code.

**Comment by Falindir** [comment]
Pour pouvoir réaliser ceci il faut regarder du coté du SituationLoder de Warbor pour lancer une configuration de warbot
