### ISSUE TITLE
Lister les équipes de Warbot Online

### ISSUE THREAD

**Issue by sbeugnon** [ProjectWarbot/Warbot-Online#27]
Afficher une page contenant la liste des équipes des joueurs de Warbot Online avec un champ de recherche par nom.

Et afficher la liste des IA présentes dans Warbot Online.

**Comment by quentinphilbert** [comment]
J'aimerais bien m'occuper de ca si possible.

**Comment by sbeugnon** [comment]
Quentin accepte l'invitation à ProjectWarbot. Et je t'assigne à cette tâche.

**Comment by quentinphilbert** [comment]
C'est fait !
