### ISSUE TITLE
Internationalisation (i18n)

### ISSUE THREAD

**Issue by sbeugnon** [ProjectWarbot/Warbot-Online#36]
Il faut repérer toutes les phrases de l'interface et les rajouter dans le fichier d'internationalisation en français et en anglais par example :
Dans le fichier webapp/WEB-INF/resources/i18n/messages.properties
team = team
welcome.home.page = Welcome on Warbot

Dans le fichier webapp/WEB-INF/resources/i18n/messages_fr_FR.properties

team = équipes
welcome.home.page = Bienvenue sur Warbot

Puis il suffit de faire en thymeleaf des <span th:text="#{team}">mot par défault</span>

**Comment by quentinphilbert** [comment]
Facile, je l'ai deja fait sous Symphony j'vais le refaire.

**Comment by geoffrey0170** [comment]
done.
