### ISSUE TITLE
Editeur de carte - BD/Model

### ISSUE THREAD

**Issue by Falindir** [ProjectWarbot/Warbot-Online#38]
Il s'agit ici réaliser la base de donnée qui va stocker les cartes créer par les utilisateurs

Carte : 
- Nom
- Description
- Niveau de difficulté  (enum : LevelTrainingConfigurationEnum)
- Créateur 
- Liste d'objet qui représente un agent que l'on crée sur la map (TrainingAgent)

Pour réaliser ceci j'ai commencé à implémenter la classe TrainingConfiguration il faut juste la compléter.

**Comment by quentinphilbert** [comment]
Fait
