### ISSUE TITLE
Editeur de carte - Service + Repository

### ISSUE THREAD

**Issue by Falindir** [ProjectWarbot/Warbot-Online#39]
Il s'agit de pouvoir réaliser le service et repository qui permet de réaliser les actions sur les cartes.
- Sauvegarder une carte 
- Charger une carte 
- Editer une carte 
- Mais aussi pouvoir réccupérer une carte d'un autre utilisateur et de pourvoir un créer une copie pour pouvoir l'éditer

**Comment by quentinphilbert** [comment]
Presque fini
