### ISSUE TITLE
Développement des interactions dans la fenêtre de partie

### ISSUE THREAD

**Issue by geoffrey0170** [ProjectWarbot/Warbot-Online#4]
Mouvements avancés (Caméra, Zoom, Follow agent)

Affichage des informations supplémentaires. (Vie, Debug message, champs de perception, contrôle de vitesse de la partie, pause)

**Comment by Falindir** [comment]
Etat d'avancement de l'issue : 
- Caméra move (100 %)
- Caméra follow agent (100 %)
- Caméra zoom (50 %)
- Vie (100 %)
- champs de perception (100 %)
- Debug message (50 %)
- contrôle de vitesse de la partie (0 %)
- pause (0 %)
