### ISSUE TITLE
Lancer plusieurs partie en streaming

### ISSUE THREAD

**Issue by geoffrey0170** [ProjectWarbot/Warbot-Online#6]
Créer un contrôleur vérifiant que les agents Warbot nécessaires à une partie sont connectés. (Voir création de nouveau Processus)

**Comment by sbeugnon** [comment]
Pour autoriser le lancement de plusieurs instances WarGame, il a fallu définir deux nouvelles classes : 
- WebLauncher un agent qui s'occupe de lancer les agents pour une instance WarGame.
- WebScheduler un agent (créé par le WebLauncher) qui s'occupe d'appeller les méthodes "doAfterTick". 

Ces deux agents sont utilisés dans le service WebGameService qui s'occupe de gérer des parties Warbot.

**Comment by sbeugnon** [comment]
Cette tâche devra être résolu par la création de processus s'occupant d'une seule partie Warbot, qui peut être commandé à distance par l'utilisateur. (Pause, Reprise, Fin demandée)

**Comment by sbeugnon** [comment]
Tâche terminée.
